import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes,randomUUID } from 'node:crypto';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createStore } from '../backend/store.mjs';
import { createApi } from '../backend/server.mjs';
const secret=()=>randomBytes(32).toString('hex');
const act=(store,token,action,id=randomUUID())=>store.action(token,{requestId:id,action});
function pair(store){const a=secret(),b=secret(),invite=secret();store.create(a,{name:'甲',invite});store.join(b,{name:'乙',invite});return {a,b,invite};}
test('两位独立身份、一次性邀请、未知访问者不能读取数据',()=>{const s=createStore();try{const {a,b,invite}=pair(s);assert.equal(s.snapshot(a).memberCount,2);assert.equal(s.snapshot(b).slot,1);assert.throws(()=>s.snapshot(secret()),/凭证无效/);assert.throws(()=>s.join(secret(),{name:'第三位',invite}),/邀请已使用/);assert.throws(()=>s.invite(b,{invite:secret()}),/只有创建者/);assert.throws(()=>s.invite(a,{invite:secret()}),/已经到齐/);assert.equal(s.db.prepare('SELECT count(*) n FROM members WHERE key_hash IN (?,?)').get(a,b).n,0);}finally{s.close();}});
test('后端决定成员与兑换金额，重复提交只执行一次',()=>{const s=createStore();try{const {a,b}=pair(s),id=randomUUID();const action={type:'study',minutes:25,person:1,amount:999999,note:'hello'};act(s,a,action,id);act(s,a,action,id);let state=s.snapshot(b).state;assert.equal(state.events.length,1);assert.equal(state.events[0].person,0);assert.equal(state.events[0].minutes,25);assert.throws(()=>act(s,b,action,id),/编号已被使用/);act(s,b,{type:'study',minutes:50,note:''});act(s,a,{type:'build',plan:'riverside',amount:999999});state=s.snapshot(b).state;assert.equal(state.events.at(-1).amount,500);assert.equal(state.events.filter(e=>e.type==='study').length,2);}finally{s.close();}});
test('只能撤销自己的未花费学习，不能透支',()=>{const s=createStore();try{const {a,b}=pair(s);act(s,a,{type:'study',minutes:25});assert.throws(()=>act(s,b,{type:'undo'}),/你还没有/);act(s,b,{type:'build',plan:'riverside'});assert.throws(()=>act(s,a,{type:'undo'}),/已投入/);assert.throws(()=>act(s,b,{type:'build',plan:'riverside'}),/先记录/);act(s,b,{type:'study',minutes:50});act(s,b,{type:'undo'});assert.equal(s.snapshot(a).state.events.length,2);}finally{s.close();}});
test('重开 SQLite 数据库后成员、进度与去重记录仍保留',()=>{const dir=mkdtempSync(join(tmpdir(),'together-home-test-')),path=join(dir,'home.sqlite');let s=createStore(path);const {a,b}=pair(s),id=randomUUID(),action={type:'study',minutes:30};act(s,a,action,id);s.close();s=createStore(path);try{assert.equal(s.snapshot(b).state.events.length,1);act(s,a,action,id);assert.equal(s.snapshot(b).state.events.length,1);}finally{s.close();rmSync(dir,{recursive:true});}});
test('HTTP 同时打卡与同时建设不会丢记录或花掉不存在的资金',async()=>{const s=createStore(),server=createApi(s,{rateLimit:false});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`,{a,b}=pair(s);const post=async(token,path,body)=>{const r=await fetch(url+'/v1/'+path,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};};try{const results=await Promise.all([post(a,'action',{requestId:randomUUID(),action:{type:'study',minutes:25}}),post(b,'action',{requestId:randomUUID(),action:{type:'study',minutes:25}})]);assert.ok(results.every(r=>r.status===200));const builds=await Promise.all([post(a,'action',{requestId:randomUUID(),action:{type:'build',plan:'riverside'}}),post(b,'action',{requestId:randomUUID(),action:{type:'build',plan:'riverside'}})]);assert.deepEqual(builds.map(r=>r.status).sort(),[200,400]);assert.equal(s.snapshot(a).state.events.filter(e=>e.type==='build').length,1);assert.equal((await post(secret(),'snapshot',{})).status,401);const denied=await fetch(url+'/v1/snapshot',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'});assert.equal(denied.status,403);assert.equal((await fetch(url+'/data/home.sqlite')).status,404);}finally{await new Promise(r=>server.close(r));s.close();}});
