import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
page.setDefaultTimeout(10000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.route('**/cloud-config.json*',route=>route.fulfill({contentType:'application/json',body:'{"apiUrl":""}'}));
  await page.goto(process.env.TEST_URL||'http://localhost:4178');
  console.log('Checking study credit and construction');
  await expect(page.locator('canvas')).toHaveAttribute('data-mode','preview');
  const beforeOrbit=await page.locator('canvas').screenshot();
  const canvasBox=await page.locator('canvas').boundingBox();
  await page.mouse.move(canvasBox.x+canvasBox.width*.4,canvasBox.y+canvasBox.height*.45);
  await page.mouse.down();
  await page.mouse.move(canvasBox.x+canvasBox.width*.6,canvasBox.y+canvasBox.height*.55,{steps:12});
  await page.mouse.up();
  await page.waitForTimeout(300);
  expect(beforeOrbit.equals(await page.locator('canvas').screenshot())).toBe(false);
  const beforeZoom=await page.locator('canvas').screenshot();
  await page.locator('#zoom-in').click();
  expect(beforeZoom.equals(await page.locator('canvas').screenshot())).toBe(false);
  await page.locator('#reset-view').click();
  await expect(page.locator('#balance')).toHaveText('$0');
  await page.locator('#study-open').click();
  await page.locator('[data-person="1"]').click();
  await page.locator('#study-note').fill('一起学会了一道题 <3');
  await page.locator('#study-form button[type=submit]').click();
  await expect(page.locator('#balance')).toHaveText('$250');
  await expect(page.locator('.journal-entry').first()).toContainText('你 学习了 25 分钟');
  await page.locator('#invest').click();
  await expect(page.locator('#balance')).toHaveText('$0');
  await expect(page.locator('canvas')).toHaveAttribute('data-mode','construction');
  await expect(page.locator('#build-percent')).toHaveText('5%');
  await page.locator('#undo').click();
  await expect(page.locator('#toast')).toContainText('已投入');
  await page.locator('[data-plan="fremont"]').click();
  await expect(page.locator('canvas')).toHaveAttribute('data-plan','fremont');
  await expect(page.locator('#build-percent')).toHaveText('0%');
  await page.locator('[data-plan="riverside"]').click();
  await expect(page.locator('#build-percent')).toHaveText('5%');
  await page.reload();
  console.log('Checking reload, source floorplan, room selection');
  await expect(page.locator('#build-percent')).toHaveText('5%');
  await page.locator('[data-flat=true]').click();
  await expect(page.locator('#floor-image')).toBeVisible();
  await expect(page.locator('#floor-image')).toHaveAttribute('src',/riverside-floor/);
  await page.locator('[data-flat=false]').click();
  await page.locator('.switch-label').click();
  await expect(page.locator('#labels-toggle')).toBeChecked();
  await page.locator('.room-label[data-room=study]').click();
  await expect(page.locator('#room-detail')).toContainText('双人书房');
  await page.locator('#exterior').click();
  console.log('Checking alternate plans and mobile');
  await page.locator('.model-panel').screenshot({path:'test-results/exterior.png'});
  for(const id of ['fremont','naperville','riverside']){await page.locator(`[data-plan=${id}]`).click();await expect(page.locator('canvas')).toHaveAttribute('data-plan',id);}
  await page.locator('#cutaway').click();
  await page.locator('.switch-label').click();
  await expect(page.locator('#labels-toggle')).not.toBeChecked();
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('canvas')).toBeVisible();
  const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
  expect(width.scroll).toBeLessThanOrEqual(width.width);
  await page.locator('.model-panel').screenshot({path:'test-results/mobile-model.png'});
  await page.locator('#study-open').click();
  await page.locator('#minutes').fill('50');
  await page.locator('#study-form button[type=submit]').click();
  await expect(page.locator('#balance')).toHaveText('$500');
  await page.locator('#undo').click();
  await expect(page.locator('#balance')).toHaveText('$0');
  expect(errors).toEqual([]);
  console.log('PASS: 3D rendering, study credit, spending, undo guards, separate plans, persistence, floor images, room picking, mobile layout; no browser errors.');
} finally {await browser.close();}
