import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { plans } from '../src/plans.js';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
page.setDefaultTimeout(10000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.route('**/cloud-config.json*',route=>route.fulfill({contentType:'application/json',body:'{"apiUrl":""}'}));
  await page.goto(process.env.TEST_URL||'http://localhost:4178');
  console.log('Checking official prices, budget filter and sorting');
  await expect(page.locator('.plan-card')).toHaveCount(6);
  await expect(page.locator('#market-price')).toHaveText('$456,900 起');
  await expect(page.locator('#price-source')).toHaveAttribute('href','https://www.mihomes.com/new-homes/ohio/columbus/riverside-plan');
  await page.locator('#plan-sort').selectOption('price-asc');
  await expect(page.locator('.plan-select').first()).toHaveAttribute('data-plan','ashland');
  await page.locator('#plan-budget').selectOption('under-450');
  await expect(page.locator('.plan-card')).toHaveCount(4);
  await expect(page.locator('#plan-title')).toHaveText('Riverside');
  await page.locator('#plan-budget').selectOption('over-450');
  await expect(page.locator('.plan-card')).toHaveCount(2);
  await page.locator('#plan-budget').selectOption('all');
  await page.locator('#plan-sort').selectOption('default');
  console.log('Checking study credit and construction');
  await expect(page.locator('canvas')).toHaveAttribute('data-mode','preview');
  const beforeOrbit=await page.locator('canvas').screenshot();
  const canvasBox=await page.locator('canvas').boundingBox();
  await page.mouse.move(canvasBox.x+canvasBox.width*.4,canvasBox.y+canvasBox.height*.45);
  await page.mouse.down();
  await page.mouse.move(canvasBox.x+canvasBox.width*.6,canvasBox.y+canvasBox.height*.55,{steps:12});
  await page.mouse.up();
  await page.waitForTimeout(300);
  expect(beforeOrbit.equals(await page.locator('canvas').screenshot())).toBe(false);
  const beforeZoom=await page.locator('canvas').screenshot();
  await page.locator('#zoom-in').click();
  expect(beforeZoom.equals(await page.locator('canvas').screenshot())).toBe(false);
  await page.locator('#reset-view').click();
  await expect(page.locator('#balance')).toHaveText('$0');
  await page.locator('#study-open').click();
  await page.locator('[data-person="1"]').click();
  await page.locator('#study-note').fill('一起学会了一道题 <3');
  await page.locator('#study-form button[type=submit]').click();
  await expect(page.locator('#balance')).toHaveText('$250');
  await expect(page.locator('.journal-entry').first()).toContainText('你 学习了 25 分钟');
  await page.locator('#invest').click();
  await expect(page.locator('#balance')).toHaveText('$0');
  await expect(page.locator('canvas')).toHaveAttribute('data-mode','construction');
  await expect(page.locator('#build-percent')).toHaveText('5%');
  await page.locator('#undo').click();
  await expect(page.locator('#toast')).toContainText('已投入');
  await page.locator('.plan-select[data-plan="fremont"]').click();
  await expect(page.locator('canvas')).toHaveAttribute('data-plan','fremont');
  await expect(page.locator('#build-percent')).toHaveText('0%');
  await page.locator('.plan-select[data-plan="riverside"]').click();
  await expect(page.locator('#build-percent')).toHaveText('5%');
  await page.reload();
  console.log('Checking reload, source floorplan, room selection');
  await expect(page.locator('#build-percent')).toHaveText('5%');
  await page.locator('[data-flat=true]').click();
  await expect(page.locator('#floor-image')).toBeVisible();
  await expect(page.locator('#floor-image')).toHaveAttribute('src',/riverside-floor/);
  await page.locator('[data-flat=false]').click();
  await page.locator('.switch-label').click();
  await expect(page.locator('#labels-toggle')).toBeChecked();
  await page.locator('.room-label[data-room=study]').click();
  await expect(page.locator('#room-detail')).toContainText('双人书房');
  await page.locator('#exterior').click();
  console.log('Checking alternate plans and mobile');
  await page.locator('.model-panel').screenshot({path:'test-results/exterior.png'});
  await page.locator('#cutaway').click();
  for(const plan of plans){
    await page.locator(`.plan-select[data-plan=${plan.id}]`).click();
    await expect(page.locator('canvas')).toHaveAttribute('data-plan',plan.id);
    await expect(page.locator('#market-price')).toHaveText('$'+plan.price.amount.toLocaleString('en-US')+' 起');
    await page.locator('[data-flat=true]').click();
    await expect(page.locator('#floor-image')).toHaveAttribute('src',new RegExp(plan.floorFile));
    await page.locator('#floor-image').evaluate(img=>img.decode());
    await page.locator('[data-flat=false]').click();
    if(['ashland','grandview','anthem'].includes(plan.id))await page.locator('.model-panel').screenshot({path:`test-results/${plan.id}-model.png`});
  }
  await page.locator('.plan-select[data-plan=riverside]').click();
  await expect(page.locator('#build-percent')).toHaveText('5%');
  await page.locator('#cutaway').click();
  await page.locator('.switch-label').click();
  await expect(page.locator('#labels-toggle')).not.toBeChecked();
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('canvas')).toBeVisible();
  const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
  expect(width.scroll).toBeLessThanOrEqual(width.width);
  await page.locator('.model-panel').screenshot({path:'test-results/mobile-model.png'});
  await page.locator('#study-open').click();
  await page.locator('#minutes').fill('50');
  await page.locator('#study-form button[type=submit]').click();
  await expect(page.locator('#balance')).toHaveText('$500');
  await page.locator('#undo').click();
  await expect(page.locator('#balance')).toHaveText('$0');
  expect(errors).toEqual([]);
  console.log('PASS: all 6 floorplans, real starting prices, filters, 3D rendering, study credit, spending, undo guards, preserved progress, floor images, room picking and mobile layout; no browser errors.');
} finally {await browser.close();}
