import {chromium,expect as baseExpect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
import {createStore} from '../backend/store.mjs';
import {createApi} from '../backend/server.mjs';
import {items,getItem} from '../src/items.js';
import {money,cloudState,studyCredit,setFocus} from './browser-helpers.mjs';

const expect=baseExpect.configure({timeout:25000});
const url=process.env.TEST_URL||'http://localhost:4178/',live=process.env.PET_LIVE_API==='1';
const store=live?null:createStore(),server=live?null:createApi(store,{rateLimit:false});if(server)await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'msedge',headless:true}),contexts=await Promise.all([browser.newContext({viewport:{width:1440,height:1100}}),browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true})]),[a,b]=await Promise.all(contexts.map(context=>context.newPage()));
const errors=[];for(const page of [a,b]){page.setDefaultTimeout(25000);page.on('pageerror',error=>errors.push(error.message));if(server)await page.route('**/cloud-config.json*',route=>route.fulfill({json:{apiUrl:`http://127.0.0.1:${server.address().port}`}}));}
async function study(page){await page.locator('#study-open').click();await page.locator('#minutes').fill('480');await setFocus(page,100);await page.locator('#study-form button[type=submit]').click();await expect(page.locator('#study-dialog')).not.toBeVisible();}
async function category(page,id){await page.locator('#shop-catalog').click();await page.locator(`[data-category=${id}]`).click();}
async function openProduct(page,id){await category(page,getItem(id).category);if(await page.locator(`[data-item="${id}"]`).count()===0)await page.locator('#shop-more').click();await page.locator(`[data-item="${id}"]`).click();await expect(page.locator('#item-preview canvas')).toHaveAttribute('data-item',id);await expect(page.locator('.checkout-total strong')).toHaveText(money(getItem(id).price));}
async function buyAndPlace(page,id,room,u,v,rotation=0){await openProduct(page,id);if(id==='cat-tree')await page.locator('#item-dialog').screenshot({path:'test-results/cats-tree-preview.png'});await page.locator('#buy-item').click();await expect(page.locator('#place-item')).toBeVisible();const owned=(await cloudState(page)).events.filter(event=>event.type==='purchase'&&event.item===id).at(-1);expect(owned.amount).toBe(getItem(id).price);await page.locator('#placement-room').selectOption(room);await expect(page.locator('#free-placement-wrap')).toBeVisible();await page.locator('#free-position-u').fill(String(u));await page.locator('#free-position-v').fill(String(v));for(let i=0;i<rotation;i++)await page.locator('#rotate-item').click();await page.locator('#place-item').click();await expect(page.locator('#item-dialog')).not.toBeVisible();expect((await cloudState(page)).placements.find(position=>position.id===owned.id)).toMatchObject({room,u,v,rotation});return owned;}
try{
  await mkdir('test-results',{recursive:true});await a.goto(url,{waitUntil:'domcontentloaded'});await a.locator('#connect-name').fill('猫房测试甲');await a.locator('#create-room').click();await expect(a.locator('#cloud-connected')).toBeVisible();await a.locator('#make-invite').click();await expect(a.locator('#invite-output')).toBeVisible();const invite=await a.locator('#invite-link').inputValue();await a.locator('#close-cloud').click();await b.goto(invite,{waitUntil:'domcontentloaded'});await b.locator('#connect-name').fill('猫房测试乙');await b.locator('#join-room').click();await expect(b.locator('#connected-summary')).toContainText('两个人都加入了');await b.locator('#close-cloud').click();
  await a.locator('#design-open').click();await a.locator('[data-design-template=cat-home]').click();await expect(a.locator('[data-design-room]')).toHaveCount(5);await expect(a.locator('#design-edit-type')).toHaveValue('cat');await expect(a.locator('#design-furnished')).not.toBeChecked();await a.locator('#design-name').fill('猫房和家具测试屋');await a.locator('#design-name').press('Tab');await a.locator('[data-design-view="3d"]').click();await expect(a.locator('#design-preview canvas')).toHaveAttribute('data-plan',/^custom-/);await a.locator('#design-preview').screenshot({path:'test-results/cats-template-preview.png'});await a.locator('#design-save').click();await expect(a.locator('#designer-dialog')).not.toBeVisible();await expect(b.locator('#plan-title')).toHaveText('猫房和家具测试屋',{timeout:20000});
  const design=(await cloudState(a)).customPlans[0],cat=design.rooms.find(room=>room.type==='cat'),living=design.rooms.find(room=>room.type==='living');expect(cat.furnished).toBe(false);expect((await cloudState(a)).events.filter(event=>event.type==='purchase')).toHaveLength(0);await expect(a.locator('#scene canvas')).toHaveAttribute('data-placed','0');
  await Promise.all([study(a),study(b)]);await expect.poll(async()=>(await cloudState(a)).events.filter(event=>event.type==='study').length,{timeout:20000}).toBe(2);const credited=studyCredit(await cloudState(a));await expect(b.locator('#balance')).toHaveText(money(credited),{timeout:20000});
  await category(a,'furniture');await expect(a.locator('.shop-card')).toHaveCount(8);await a.locator('#shop-more').click();await expect(a.locator('.shop-card')).toHaveCount(items.filter(item=>item.category==='furniture').length);await a.locator('#shop').screenshot({path:'test-results/furniture-catalog-desktop.png'});await category(b,'cats');await expect(b.locator('.shop-card')).toHaveCount(8);await b.locator('#shop-more').click();await expect(b.locator('.shop-card')).toHaveCount(10);await b.locator('#shop').screenshot({path:'test-results/cats-catalog-mobile.png'});
  const bought=[];bought.push(await buyAndPlace(a,'cat-tree',cat.id,20,20));bought.push(await buyAndPlace(b,'cat-condo',cat.id,75,20,1));bought.push(await buyAndPlace(a,'cat-litter',cat.id,20,75,2));bought.push(await buyAndPlace(b,'cat-fountain',cat.id,75,75));bought.push(await buyAndPlace(a,'cat-feeder',cat.id,50,50));bought.push(await buyAndPlace(b,'furniture-sofa',living.id,25,45,1));bought.push(await buyAndPlace(a,'furniture-bookcase',living.id,75,25,2));bought.push(await buyAndPlace(a,'furniture-tv',living.id,50,80));bought.push(await buyAndPlace(b,'furniture-microwave',living.id,80,65,1));
  const spent=bought.reduce((sum,event)=>sum+event.amount,0);expect(spent).toBe(bought.reduce((sum,event)=>sum+getItem(event.item).price,0));await expect(b.locator('#owned-count')).toHaveText(String(bought.length),{timeout:20000});await expect(b.locator('#scene canvas')).toHaveAttribute('data-placed',String(bought.length),{timeout:20000});await expect(a.locator('#balance')).toHaveText(money(credited-spent));await expect(b.locator('#balance')).toHaveText(money(credited-spent));await expect(a.locator('#build-percent')).toHaveText('0%');expect((await cloudState(a)).placements.filter(position=>position.room===cat.id)).toHaveLength(5);
  await category(b,'cats');await b.locator('#shop-inventory').click();await expect(b.locator('[data-owned]')).toHaveCount(5);await b.locator(`[data-owned="${bought[0].id}"]`).click();await b.locator('#free-position-u').fill('30');await b.locator('#free-position-v').fill('30');await b.locator('#rotate-item').click();await b.locator('#item-dialog').screenshot({path:'test-results/cats-placement-mobile.png'});const dimensions=await b.locator('#item-dialog').evaluate(element=>({scroll:element.scrollWidth,client:element.clientWidth,page:document.documentElement.scrollWidth,viewport:innerWidth}));expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.client);expect(dimensions.page).toBeLessThanOrEqual(dimensions.viewport);await b.locator('#place-item').click();await expect(b.locator('#item-dialog')).not.toBeVisible();await expect.poll(async()=>(await cloudState(a)).placements.find(position=>position.id===bought[0].id),{timeout:20000}).toMatchObject({u:30,v:30,rotation:1,room:cat.id});
  await a.locator('#reset-view').click();if(!await a.locator('#labels-toggle').isChecked())await a.locator('.switch-label').click();await a.locator('#top-view').click();await a.locator('#scene').screenshot({path:'test-results/cats-room-top.png'});await a.locator('#reset-view').click();await a.locator('.model-panel').screenshot({path:'test-results/cats-room-3d.png'});await b.locator('#reset-view').click();await b.locator('.model-panel').screenshot({path:'test-results/cats-room-mobile.png'});
  await b.locator('#ledger-wallet-open').click();await b.locator('#ledger-type').selectOption('purchase');await expect(b.locator('.ledger-entry')).toHaveCount(bought.length);await expect(b.locator('#ledger-expense')).toHaveText(money(spent));await expect(b.locator('#ledger-balance')).toHaveText(money(credited-spent));for(const owned of bought)await expect(b.locator(`[data-event-id="${owned.id}"] .ledger-amount`)).toHaveText('− '+money(owned.amount));await b.locator('#ledger-person').selectOption('0');await expect(b.locator('.ledger-entry')).toHaveCount(5);await b.locator('#ledger-person').selectOption('1');await expect(b.locator('.ledger-entry')).toHaveCount(4);await b.locator('#ledger-close').click();
  const saved=await cloudState(a);await Promise.all([a.reload({waitUntil:'domcontentloaded'}),b.reload({waitUntil:'domcontentloaded'})]);await expect(a.locator('#sync-open')).toContainText('已联机');await expect(b.locator('#sync-open')).toContainText('已联机');await expect(a.locator('#scene canvas')).toHaveAttribute('data-placed',String(bought.length));await expect(b.locator('#scene canvas')).toHaveAttribute('data-placed',String(bought.length));expect((await cloudState(a)).events).toEqual(saved.events);expect((await cloudState(b)).placements).toEqual(saved.placements);expect((await cloudState(b)).customPlans).toEqual(saved.customPlans);
  await a.locator('.plan-select[data-plan=riverside]').click();await expect(a.locator('#plan-title')).toHaveText('Riverside');await expect(b.locator('#scene canvas')).toHaveAttribute('data-placed','0',{timeout:20000});await a.locator(`[data-custom-select="${design.id}"]`).click();await expect(a.locator('#plan-title')).toHaveText(design.name);await expect(b.locator('#scene canvas')).toHaveAttribute('data-placed',String(bought.length),{timeout:20000});await expect(b.locator('#balance')).toHaveText(money(credited-spent));expect(errors).toEqual([]);
  console.log(`CATS + FURNITURE BROWSER PASSED (${live?'public API':'isolated API'}): 5-room template, ${items.filter(item=>['furniture','cats'].includes(item.category)).length} furniture/cat products, 9 purchases, 2 expansion combinations, 5 cat-room placements, partner rotation, ledger, reload, 3D and mobile; ${url}`);
}finally{await browser.close();if(server){await new Promise(resolve=>server.close(resolve));store.close();}}
