import {chromium,expect} from '@playwright/test';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import {freshState,study,purchase,balance,validate} from '../src/state.js';
import {ledgerEntries} from '../src/ledger.js';
import {createStore} from '../backend/store.mjs';
import {createApi} from '../backend/server.mjs';
import {money,localState,buildPercent} from './browser-helpers.mjs';

const url=process.env.TEST_URL||'http://localhost:4178/';
const store=createStore(':memory:',{studyRoll:()=>500}),server=createApi(store,{rateLimit:false});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];
const secret=()=>randomBytes(32).toString('hex'),act=(token,action)=>store.action(token,{requestId:randomUUID(),action});
function watch(page){page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push(error.message));}
async function dates(page,from,to){await page.locator('#ledger-from').fill(from);await page.locator('#ledger-from').press('Tab');await page.locator('#ledger-to').fill(to);await page.locator('#ledger-to').press('Tab');}
async function assertRows(page,state){const entries=new Map(ledgerEntries(state).map(e=>[e.event.id,e]));for(const id of await page.locator('.ledger-entry').evaluateAll(nodes=>nodes.map(node=>node.dataset.eventId))){const entry=entries.get(id),row=page.locator(`[data-event-id="${id}"]`);expect(entry).toBeTruthy();await expect(row.locator('.ledger-amount')).toHaveText((entry.incoming?'+':'−')+' '+money(entry.amount));await expect(row.locator('.ledger-running')).toHaveText('累计余额 '+money(entry.running));}}
try{
  await mkdir('test-results',{recursive:true});
  let initial={...freshState(),names:['<img>','乙'],events:[{id:'old-one',type:'study',person:0,minutes:480,note:'<img src=x onerror=alert(1)>',at:'2026-09-01T12:00:00Z'},{id:'old-two',type:'study',person:1,minutes:480,note:'历史学习',at:'2026-09-01T12:01:00Z'},{id:'old-build',type:'build',plan:'riverside',amount:500,at:'2026-09-01T12:02:00Z'}]};
  for(let i=0;i<30;i++){initial=study(initial,{person:i%2,minutes:1},{roll:()=>500});initial.events.at(-1).at=`2026-09-${i<15?'02':'03'}T12:${String(i%15).padStart(2,'0')}:00Z`;}
  initial=purchase(initial,{item:'decor-plant',person:1});
  // This fixture predates the price reduction: retain its original v1 bill.
  const historicalPurchase=initial.events.at(-1);historicalPurchase.at='2026-09-03T13:00:00Z';historicalPurchase.amount=100;delete historicalPurchase.priceVersion;
  initial=study(initial,{person:1,minutes:25,focus:0},{roll:()=>0});initial.events.at(-1).at='2026-09-04T12:00:00Z';validate(initial);
  const local=await browser.newPage({viewport:{width:1440,height:1100}});watch(local);await local.route('**/cloud-config.json*',r=>r.fulfill({json:{apiUrl:''}}));await local.addInitScript(state=>{if(!localStorage.getItem('together-home-v1'))localStorage.setItem('together-home-v1',JSON.stringify(state));},initial);await local.goto(url);
  await expect(local.locator('#construction-total')).toHaveText('$456,900');await expect(local.locator('#construction-paid')).toHaveText('$500');await expect(local.locator('#construction-remaining')).toHaveText('$456,400');await expect(local.locator('#build-percent')).toHaveText('0.1%');await local.locator('#construction-details summary').click();await expect(local.locator('#phases .phase')).toHaveCount(20);await expect(local.locator('#construction-phase-total')).toHaveText('$456,900');expect(await localState(local)).toEqual(initial);
  await local.locator('#ledger-wallet-open').click();await expect(local.locator('#ledger-balance')).toHaveText(money(balance(initial)));await expect(local.locator('#ledger-income')).toHaveText('$10,100');await expect(local.locator('#ledger-expense')).toHaveText('$600');await expect(local.locator('.ledger-entry')).toHaveCount(25);await expect(local.locator('#ledger-page')).toHaveText('第 1 / 2 页');await assertRows(local,initial);
  await local.locator('#ledger-next').click();await expect(local.locator('.ledger-entry')).toHaveCount(10);await expect(local.locator('[data-event-id=old-one]')).toContainText('<img src=x onerror=alert(1)>');await expect(local.locator('#ledger-items img')).toHaveCount(0);await assertRows(local,initial);
  await local.locator('#ledger-type').selectOption('purchase');await expect(local.locator('.ledger-entry')).toHaveCount(1);await assertRows(local,initial);await expect(local.locator('#ledger-balance')).toHaveText('$9,500');await local.locator('#ledger-type').selectOption('build');await local.locator('#ledger-person').selectOption('shared');await expect(local.locator('.ledger-entry')).toHaveCount(1);await expect(local.locator('.ledger-entry')).toContainText('早期施工');
  await local.locator('#ledger-reset').click();await dates(local,'2026-09-02','2026-09-02');await expect(local.locator('.ledger-entry')).toHaveCount(15);await assertRows(local,initial);await local.locator('#ledger-person').selectOption('1');await expect(local.locator('.ledger-entry')).toHaveCount(7);await dates(local,'2026-09-04','2026-09-02');await expect(local.locator('#ledger-error')).toContainText('结束日期');await expect(local.locator('.ledger-entry')).toHaveCount(0);await local.locator('#ledger-reset').click();await local.locator('#ledger-dialog').screenshot({path:'test-results/construction-ledger-desktop.png'});
  await local.setViewportSize({width:390,height:844});const dimensions=await local.locator('#ledger-dialog').evaluate(el=>({scroll:el.scrollWidth,client:el.clientWidth,page:document.documentElement.scrollWidth,viewport:innerWidth}));expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.client);expect(dimensions.page).toBeLessThanOrEqual(dimensions.viewport);await local.locator('#ledger-dialog').screenshot({path:'test-results/construction-ledger-mobile.png'});await local.locator('#ledger-close').click();
  await local.setViewportSize({width:1440,height:1100});await local.locator('#design-open').click();await local.locator('[data-design-template=studio]').click();await expect(local.locator('#design-budget')).toHaveValue('450000');await local.locator('#design-budget').fill('999');await local.locator('#design-save').click();await expect(local.locator('#designer-dialog')).toBeVisible();await expect(local.locator('#design-budget')).toHaveValue('999');expect((await localState(local)).customPlans||[]).toHaveLength(0);
  await local.locator('#design-budget').fill('450001');await local.locator('#design-name').fill('零头预算测试房');await local.locator('#design-save').click();await expect(local.locator('#designer-dialog')).not.toBeVisible();await expect(local.locator('#construction-total')).toHaveText('$450,001');await expect(local.locator('#construction-phase-total')).toHaveText('$450,001');await local.locator('#invest').click();await expect(local.locator('#construction-paid')).toHaveText('$9,000');await expect(local.locator('#balance')).toHaveText('$500');const afterBuild=await localState(local),custom=afterBuild.customPlans[0];expect(custom.budget).toBe(450001);expect(afterBuild.events.slice(0,initial.events.length)).toEqual(initial.events);expect(afterBuild.events.at(-1)).toMatchObject({type:'build',person:0,stage:'survey-permits',amount:9000,plan:custom.id});
  await local.locator('#edit-design').click();await local.locator('#design-budget').fill('8999');await local.locator('#design-save').click();await expect(local.locator('#designer-dialog')).toBeVisible();await expect(local.locator('#design-budget')).toHaveValue('8999');expect((await localState(local)).customPlans[0].budget).toBe(450001);await local.locator('#design-budget').fill('600003');await local.locator('#design-save').click();await expect(local.locator('#designer-dialog')).not.toBeVisible();await expect(local.locator('#construction-total')).toHaveText('$600,003');await expect(local.locator('#construction-paid')).toHaveText('$9,000');await expect(local.locator('#balance')).toHaveText('$500');await expect(local.locator('#build-percent')).toHaveText(buildPercent(9000,custom.id,await localState(local)));await local.reload();expect((await localState(local)).events).toEqual(afterBuild.events);await expect(local.locator('#construction-total')).toHaveText('$600,003');await local.close();
  console.log('PASS: all20 pricedsteps, legacycash preservation, full paginated/filtered ledger, mobilelayout, invalidbudget blocks save and exact oddbudget persists');

  const aToken=secret(),bToken=secret(),invite=secret();store.create(aToken,{name:'账本甲',invite});store.join(bToken,{name:'账本乙',invite});for(let i=0;i<30;i++)act(i%2?aToken:bToken,{type:'study',minutes:100});act(aToken,{type:'build',plan:'riverside'});act(bToken,{type:'purchase',item:'decor-plant'});
  const paired=[];for(const [token,viewport]of [[aToken,{width:1440,height:1100}],[bToken,{width:390,height:844}]]){const context=await browser.newContext({viewport}),page=await context.newPage();watch(page);const snapshot=store.snapshot(token);await page.addInitScript(session=>localStorage.setItem('together-home-session-v1',JSON.stringify(session)),{token,roomId:snapshot.roomId,slot:snapshot.slot,memberCount:snapshot.memberCount,cached:snapshot.state});await page.route('**/cloud-config.json*',r=>r.fulfill({json:{apiUrl:`http://127.0.0.1:${server.address().port}`}}));await page.goto(url);await expect(page.locator('#sync-open')).toContainText('已联机');paired.push(page);}
  const [a,b]=paired;await b.locator('#ledger-open').click();await expect(b.locator('.ledger-entry')).toHaveCount(25);await b.locator('#ledger-type').selectOption('build');await b.locator('#ledger-person').selectOption('0');await expect(b.locator('.ledger-entry')).toHaveCount(1);await expect(b.locator('.ledger-entry')).toContainText('测量与手续');await b.locator('#ledger-reset').click();
  await a.locator('#study-open').click();await a.locator('#minutes').fill('25');await a.locator('#study-form button[type=submit]').click();await expect(a.locator('#study-dialog')).not.toBeVisible();const credited=store.snapshot(aToken).state.events.at(-1);await expect(b.locator(`[data-event-id="${credited.id}"]`)).toHaveCount(1);await expect(b.locator('#ledger-balance')).toHaveText(money(balance(store.snapshot(aToken).state)));
  await b.locator('#ledger-close').click();await b.locator('#invest').click();await expect(b.locator('#construction-paid')).toHaveText('$22,845');const built=store.snapshot(bToken).state.events.at(-1);expect(built).toMatchObject({person:1,stage:'clear-grade',amount:13707});await a.locator('#ledger-open').click();await expect(a.locator(`[data-event-id="${built.id}"]`)).toHaveCount(1);await b.locator('#ledger-open').click();await assertRows(a,store.snapshot(aToken).state);await assertRows(b,store.snapshot(bToken).state);expect(await a.locator('.ledger-entry').evaluateAll(rows=>rows.map(r=>r.dataset.eventId))).toEqual(await b.locator('.ledger-entry').evaluateAll(rows=>rows.map(r=>r.dataset.eventId)));await b.reload();await expect(b.locator('#construction-paid')).toHaveText('$22,845');await b.locator('#ledger-open').click();await expect(b.locator(`[data-event-id="${built.id}"]`)).toHaveCount(1);expect(errors).toEqual([]);
  console.log('CONSTRUCTION + LEDGER BROWSER PASSED: paired live updates, recordedactor/stage, matchingmoney and reload persistence (isolated API)');
}finally{await browser.close();await new Promise(r=>server.close(r));store.close();}
