import './style.css';
import { plans,getPlan as resolvePlan,phases,totalCost } from './plans.js';
import { STORAGE_KEY,freshState,validate,balance,invested,progress,study,build,undoStudy,inventory } from './state.js';
import { createScene } from './scene.js';
import { createCloud, SESSION_KEY } from './cloud.js';
import { createShop } from './shop.js';
import { itemName } from './items.js';
import { createDesigner } from './designer.js';
import { designToPlan,planImage } from './designs.js';
import { DEFAULT_FOCUS,focusLabel,rewardRange,studyReward } from './rewards.js';
const getPlan=id=>resolvePlan(id,state);

const icon = (name,size=20) => `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',rotate:'<path d="M20 9a8 8 0 1 0 0 7M20 4v5h-5"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',layers:'<path d="m3 8 9-5 9 5-9 5Zm0 5 9 5 9-5M3 18l9 5 9-5"/>',book:'<path d="M12 5c-3-2-7-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-3-1-6-1-9 1Z"/><path d="M12 5v15"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',check:'<path d="m5 12 4 4L19 6"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3" fill="currentColor"/><circle cx="16" cy="17" r="3" fill="currentColor"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/>'})[name]||''}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'$'+n.toLocaleString('en-US');
const $=s=>document.querySelector(s);
let storageIssue=false;
function read(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?validate(JSON.parse(raw)):freshState();}catch{storageIssue=true;return freshState();}}
let state=read(),preview=true,interior=true,labels=false,person=0,selectedRoom=null,flat=false,scene;
let cloud,networkBusy=false,connectionStatus='loading',shop,designer,mutationError='',sceneKey='',studyFormBusy=false;
const isCloud=()=>!!cloud?.session?.roomId;
document.querySelector('#app').innerHTML=`
<header class="header"><a class="brand" href="#" aria-label="一起盖房主页"><span class="brand-mark">${icon('home',25)}</span><span>一起盖房<small>STUDY & BUILD</small></span></a><nav><span class="nav-active">盖房子</span><button id="history-nav">学习记录</button></nav><div class="header-end"><span class="local-status"><i></i> 本机模式 · 尚未联机</span><button class="icon-button" id="settings" aria-label="设置与存档">${icon('settings')}</button></div></header>
<main><section class="intro"><div><div class="eyebrow"><span></span> STUDY & BUILD</div><h1>学一会儿，<em>盖一点房子。</em></h1><p>挑个户型，学完打卡，攒点游戏资金一起盖房。</p></div><div class="couple"><div class="avatars"><span id="avatar-a">我</span><span id="avatar-b">你</span></div><div><b id="together-names">我 & 你</b><small>一起打卡，共用余额</small></div></div></section>
<div class="workspace"><aside class="catalog"><div class="section-heading"><div><span class="eyebrow">FLOORPLANS</span><h2>先挑个户型</h2></div><span class="count" id="plan-count">${String(plans.length).padStart(2,'0')}</span></div><div class="location">${icon('pin',14)} Columbus, Ohio · 真实户型参考</div><div class="catalog-controls"><label for="plan-sort">排序<select id="plan-sort"><option value="default">默认顺序</option><option value="price-asc">价格从低到高</option><option value="price-desc">价格从高到低</option><option value="area-desc">基础面积从大到小</option></select></label><label for="plan-budget">官方起价<select id="plan-budget"><option value="all">全部预算</option><option value="under-450">$450,000 以下</option><option value="over-450">$450,000 及以上</option></select></label></div><p class="catalog-help">${plans.length} 套单层户型 · 按官方起价筛选<br>价格查询：2026-09-20</p><div id="plan-cards"></div><a class="inspiration" href="https://www.redfin.com/OH/Columbus/850-Katherines-Ridge-Ln-43235/home/75691189" target="_blank" rel="noopener noreferrer">${icon('heart',16)}<span>参考房源<small>850 Katherines Ridge Ln ↗</small></span></a></aside>
<section class="model-panel"><div class="model-heading"><div><span class="eyebrow">CURRENT PLAN</span><h2 id="plan-title"></h2></div><div class="segmented" id="view-switch"><button class="active" data-flat="false">3D 看房</button><button data-flat="true">原始平面图</button></div></div>
<div class="scene-wrap"><div id="scene"></div><div class="flat-view" id="flat-view" hidden><img id="floor-image" alt="开发商公开的原始一层平面图"><a id="floor-full" target="_blank" rel="noopener">打开大图 ↗</a></div><div class="scene-top"><span class="scene-badge" id="mode-badge"></span><button class="light-button" id="toggle-preview">${icon('layers',16)} <span>查看施工进度</span></button></div><div class="scene-tools"><button aria-label="放大" id="zoom-in">${icon('plus')}</button><button aria-label="缩小" id="zoom-out">${icon('minus')}</button><span></span><button aria-label="俯视户型" id="top-view">${icon('layers')}</button><button aria-label="重置视角" id="reset-view">${icon('rotate')}</button></div><div class="scene-bottom"><span class="orbit-hint">拖动旋转 · 滚轮 / 双指缩放 · 点击房间</span><span class="compass">N<span>↑</span></span></div><div id="room-detail" hidden></div></div>
<div class="view-toolbar"><div class="segmented"><button id="cutaway" class="active">${icon('layers',16)} 看室内</button><button id="exterior">${icon('home',16)} 看外观</button></div><label class="switch-label"><input id="labels-toggle" type="checkbox"><span class="switch"></span>房间名称</label><span class="daylight">${icon('sun',16)} 日光模式</span></div>
<div class="plan-note"><div><span class="tiny-label">LAYOUT</span><h3 id="plan-tagline"></h3><p id="plan-description"></p></div><a id="source-link" target="_blank" rel="noopener noreferrer">查看官方户型 ${icon('arrow',16)}</a></div><div class="market-price"><div><span class="tiny-label">REAL HOME PRICE · USD</span><div class="market-amount"><strong id="market-price"></strong><span>官方户型起价</span></div><p id="market-location"></p></div><a id="price-source" target="_blank" rel="noopener noreferrer">查看价格来源 ↗</a><p class="price-context">开发商在 Columbus 地区的户型起价，不是某套现房的挂牌价。社区、地块和选配会影响最终报价。<span>查询日期：<time id="price-date"></time> · 手动核对，非实时行情</span></p></div><p class="source-note">来源：M/I Homes Columbus 公开户型 · 3D 为平面图的简化重建，仅展示一层；层高、家具与外观为示意。</p></section>
<aside class="progress-panel"><div class="section-heading"><div><span class="eyebrow">SHARED BALANCE</span><h2>打卡攒资金</h2></div>${icon('heart',19)}</div><div class="wallet"><span>共同余额 <small>游戏资金</small></span><strong id="balance">$0</strong><div class="wallet-foot"><span>基础 $10 / 分钟</span><b>按投入状态浮动</b></div></div><button id="study-open" class="primary">${icon('plus',18)} 记一次学习</button><div id="people-stats" class="people-stats"></div><div class="build-heading"><h3>施工进度</h3><span id="build-percent">0%</span></div><div class="progress-track"><i id="overall-progress"></i></div><div id="phases"></div><button class="build-button" id="invest"></button><p class="virtual-note">这里的金额都是游戏资金，和实际存款、建房费用无关。</p><div class="quote">学完记一下，<br>有余额就能接着盖。<span>LOG STUDY. KEEP BUILDING.</span></div></aside></div>
<section class="journal" id="journal"><div class="journal-header"><div><span class="eyebrow">ACTIVITY LOG</span><h2>最近的记录</h2></div><button id="undo" class="text-button">撤销最近一次学习</button></div><div id="journal-items"></div></section><footer><span>一起盖房 · 学习打卡，顺便盖房。</span><span>本机记录保存在浏览器里，可在设置中导出备份。</span></footer></main>
<dialog id="study-dialog"><form id="study-form"><div class="dialog-heading"><div><span class="eyebrow">LOG STUDY</span><h2>刚才学了多久？</h2></div><button type="button" class="icon-button close-dialog" aria-label="关闭">${icon('close')}</button></div><p class="dialog-desc">记下时长和投入状态，攒点游戏资金。基础每分钟 $10，实际金额会小幅浮动。</p><label class="field-label">谁学的？</label><div class="person-select" id="person-select"></div><label class="field-label" for="minutes">学习时长</label><div class="duration-options"><button type="button" data-minutes="25" class="selected">25 分钟</button><button type="button" data-minutes="50">50 分钟</button><button type="button" data-minutes="90">90 分钟</button></div><div class="minutes-input"><input id="minutes" type="number" min="1" max="480" step="1" value="25" required><span>分钟 · 可自定义</span></div><div class="focus-field"><div class="focus-heading"><label class="field-label" for="study-focus">投入状态</label><output id="focus-value" for="study-focus">正常发挥 · 50</output></div><input id="study-focus" type="range" min="0" max="100" step="1" value="${DEFAULT_FOCUS}" aria-describedby="focus-help focus-scale"><div class="focus-scale" id="focus-scale"><span>有点分心</span><span>很投入</span></div><p id="focus-help">按刚才的状态选就好。越投入，平均拿到的资金越多。</p></div><label class="field-label" for="study-note">学了什么？ <small>选填</small></label><input id="study-note" maxlength="120" placeholder="比如：看了两节课，做了几道题"><div class="reward study-reward" aria-live="polite"><div><span>预计入账</span><small id="reward-average"></small></div><strong id="reward-amount"></strong></div><p class="reward-help">提交时随机小幅浮动，以实际入账为准。每笔只结算一次。</p><button class="primary" type="submit">保存这次学习 ${icon('arrow',17)}</button><p class="form-error" id="study-error" role="alert"></p></form></dialog>
<dialog id="settings-dialog"><div class="dialog-heading"><div><span class="eyebrow">SETTINGS</span><h2>设置</h2></div><button class="icon-button close-dialog" aria-label="关闭">${icon('close')}</button></div><form id="names-form"><label class="field-label" for="name-a">怎么称呼</label><div class="name-inputs"><input id="name-a" required maxlength="16" placeholder="我" aria-label="第一位的称呼"><span>&</span><input id="name-b" required maxlength="16" placeholder="你" aria-label="第二位的称呼"></div><button class="primary" type="submit">保存称呼</button></form><div class="settings-block"><h3>存档和备份</h3><p>本机记录保存在这个浏览器里。可以导出备份，也可以在另一台设备上导入。</p><div class="backup-buttons"><button id="export-save">${icon('download',16)} 导出存档</button><button id="import-save">导入存档</button><input type="file" id="import-file" accept="application/json,.json" hidden></div><p class="muted">导入会替换本机记录，操作前会再确认一次。</p></div><div class="settings-block"><h3>关于户型</h3><p>${plans.length} 个户型来自 M/I Homes 的 Columbus 页面。模型保留了主要房间的位置，尺寸、门窗、外观和家具做了简化，只展示一层。游戏里把一间次卧改成了双人书房。官方房价只用于选房参考，学习换来的游戏资金和每套 $5,500 的施工目标不变。</p></div></dialog>
<dialog id="import-dialog"><div class="dialog-heading"><h2>导入这份存档？</h2><button class="icon-button close-dialog" aria-label="关闭">${icon('close')}</button></div><p id="import-summary"></p><p>将替换当前浏览器内的称呼、学习、建设、购买和摆放记录。</p><div class="backup-buttons"><button id="import-cancel">取消</button><button id="import-confirm" class="primary">替换并导入</button></div></dialog><div id="toast" role="status" aria-live="polite"></div>`;

function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4300);}
function commit(next){validate(next);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}catch{throw Error('浏览器无法保存记录，请检查存储权限或空间。');}state=next;render();}
async function mutate(fn,action){mutationError='';if(networkBusy){mutationError='上一笔操作正在保存，稍等一下。';return false;}networkBusy=true;try{if(isCloud()){return await cloud.action(action);}else{const raw=localStorage.getItem(STORAGE_KEY);const current=raw?validate(JSON.parse(raw)):state;const next=fn(current);commit(next);return {requestId:next.events.at(-1)?.id};}}catch(e){mutationError=e.message;toast(e.message);return false;}finally{networkBusy=false;}}
function sceneUpdate(){if(!scene)return;const owned=inventory(state),key=JSON.stringify([state.selected,preview,interior,labels,invested(state),owned,state.placements,state.customPlans?.find(d=>d.id===state.selected)]);if(key!==sceneKey){scene.update(getPlan(state.selected),{preview,interior,labels,amount:invested(state),inventory:owned,placements:state.placements||[]});sceneKey=key;}scene.select(selectedRoom);}
function selectRoom(id){selectedRoom=id;scene.select(id);const r=getPlan(state.selected).rooms.find(r=>r.id===id);const box=$('#room-detail');if(!r){box.hidden=true;return;}box.hidden=false;box.innerHTML=`<span class="tiny-label">ROOM DETAILS</span><strong>${esc(r.name)}</strong><span>${r.type==='study'?'两张桌子，可以各占一边。':r.type==='living'?'沙发、茶几，学完来这儿歇一会儿。':r.type==='bed'?'放张床，留点走动的空间。':'转个角度，或者放大看看。'}</span><button aria-label="关闭房间信息">×</button>`;box.querySelector('button').onclick=()=>{selectedRoom=null;box.hidden=true;scene.select(null);};}
function renderCatalog(){
  if($('#custom-plan-cards')){
    $('#custom-plan-label').hidden=!(state.customPlans||[]).length;
    $('#custom-plan-cards').innerHTML=(state.customPlans||[]).map(d=>{const p=designToPlan(d);return '<article class="custom-plan-card '+(d.id===state.selected?'selected':'')+'"><button data-custom-select="'+d.id+'" aria-pressed="'+(d.id===state.selected)+'"><img alt="自定义户型平面图" src="'+planImage(d)+'"><span><h3>'+esc(d.name)+'</h3><p>'+p.areaM2+' m² · '+d.rooms.length+' 个房间</p></span></button><div class="custom-plan-actions"><button data-custom-edit="'+d.id+'">编辑户型 / 装修</button></div></article>';}).join('');
    $('#custom-plan-cards').querySelectorAll('[data-custom-select]').forEach(b=>b.onclick=async()=>{selectedRoom=null;$('#room-detail').hidden=true;if(await mutate(s=>({...s,selected:b.dataset.customSelect}),{type:'select',plan:b.dataset.customSelect})){scene.home();}});
    $('#custom-plan-cards').querySelectorAll('[data-custom-edit]').forEach(b=>b.onclick=()=>designer.open(b.dataset.customEdit));
  }
  const sort=$('#plan-sort').value,budget=$('#plan-budget').value;
  const visible=plans.filter(p=>budget==='all'||(budget==='under-450'?p.price.amount<450000:p.price.amount>=450000));
  if(sort==='price-asc')visible.sort((a,b)=>a.price.amount-b.price.amount);
  if(sort==='price-desc')visible.sort((a,b)=>b.price.amount-a.price.amount);
  if(sort==='area-desc')visible.sort((a,b)=>Number(b.area.split('–')[0].replaceAll(',',''))-Number(a.area.split('–')[0].replaceAll(',','')));
  $('#plan-count').textContent=String(visible.length).padStart(2,'0');
  $('#plan-cards').innerHTML=visible.map((p,i)=>`<article class="plan-card ${p.id===state.selected?'selected':''}"><button class="plan-select" data-plan="${p.id}" aria-pressed="${p.id===state.selected}"><div class="plan-photo"><img src="${import.meta.env.BASE_URL}references/${p.id}-exterior.jpg" alt="${p.name} 官方外观示意" loading="lazy"><span>${String(plans.indexOf(p)+1).padStart(2,'0')} / RANCH</span>${p.id===state.selected?`<i>${icon('check',14)}</i>`:''}</div><div class="plan-card-body"><div><h3>${p.name}</h3><span>${icon('arrow',16)}</span></div><p>${p.area} ft² <b>·</b> ${p.beds} 卧 <b>·</b> ${p.baths} 卫</p><div class="plan-price"><strong>${money(p.price.amount)}<small>起</small></strong><span>官方起价</span></div><span class="plan-tag">${p.tag}</span></div></button></article>`).join('');
  $('#plan-cards').querySelectorAll('[data-plan]').forEach(b=>b.onclick=async()=>{if(b.dataset.plan===state.selected)return;selectedRoom=null;$('#room-detail').hidden=true;if(await mutate(s=>({...s,selected:b.dataset.plan}),{type:'select',plan:b.dataset.plan})){scene.home();toast(`已切换为 ${getPlan(state.selected).name}。各个户型的施工进度单独保存。`);}});
}
$('#plan-sort').onchange=()=>{renderCatalog();$('#plan-cards').scrollTo(0,0);};
$('#plan-budget').onchange=()=>{renderCatalog();$('#plan-cards').scrollTo(0,0);};
function render(){const p=getPlan(state.selected),funds=balance(state),amount=invested(state),stages=progress(amount);$('#balance').textContent=money(funds);$('#plan-title').textContent=p.name;$('#plan-tagline').textContent=p.title;$('#plan-description').textContent=p.description;
  $('#source-link').hidden=!!p.custom;$('.market-price').hidden=!!p.custom;$('#custom-design-note').hidden=!p.custom;
  $('#floor-image').src=p.custom?planImage(state.customPlans.find(d=>d.id===p.id)):import.meta.env.BASE_URL+'references/'+p.floorFile;$('#floor-full').href=$('#floor-image').src;$('#floor-image').alt=p.custom?p.name+' 自定义平面图':'M/I Homes '+p.name+' 原始一层平面图';
  $('#floor-full').textContent=p.custom?'下载平面图 ↓':'打开大图 ↗';if(p.custom)$('#floor-full').setAttribute('download','my-floorplan.svg');else $('#floor-full').removeAttribute('download');
  $('[data-flat=true]').textContent=p.custom?'我的平面图':'原始平面图';
  $('.source-note').textContent=p.custom?'自定义单层户型 · 房间尺寸以米计。墙体、屋顶和家具为游戏内示意。':'来源：M/I Homes Columbus 公开户型 · 3D 为平面图的简化重建，仅展示一层；层高、家具与外观为示意。';
  if(!p.custom){$('#source-link').href=p.source;$('#market-price').textContent=money(p.price.amount)+' 起';$('#market-location').textContent=p.location;$('#price-source').href=p.price.source;$('#price-date').textContent=p.price.checkedAt;$('#price-date').dateTime=p.price.checkedAt;}
  renderCatalog();
  $('#together-names').textContent=state.names.join(' & ');$('#avatar-a').textContent=state.names[0].slice(0,1);$('#avatar-b').textContent=state.names[1].slice(0,1);
  $('#people-stats').innerHTML=state.names.map((n,i)=>{const mins=state.events.filter(e=>e.type==='study'&&e.person===i).reduce((n,e)=>n+e.minutes,0);return `<div><span class="small-avatar person-${i}">${esc(n.slice(0,1))}</span><span>${esc(n)}<b>${mins} <small>分钟</small></b></span></div>`;}).join('');
  $('#build-percent').textContent=Math.round(amount/totalCost*100)+'%';$('#overall-progress').style.width=amount/totalCost*100+'%';const nextIndex=stages.findIndex(p=>p.ratio<1);
  $('#phases').innerHTML=stages.map((p,i)=>`<div class="phase ${p.ratio===1?'done':i===nextIndex?'current':''}"><span class="phase-marker">${p.ratio===1?icon('check',13):`0${i+1}`}</span><div><b>${p.name}</b><span>${p.ratio===1?'已完成':i===nextIndex?`${money(p.paid)} / ${money(p.cost)}`:'上一阶段完成后解锁'}</span>${i===nextIndex?`<div class="phase-track"><i style="width:${p.ratio*100}%"></i></div>`:''}</div><span class="phase-end">${p.ratio===1?'✓':i===nextIndex?'进行中':'—'}</span></div>`).join('');
  const next=stages.find(s=>s.ratio<1);$('#invest').disabled=!next||funds<=0;$('#invest').innerHTML=next?`${icon('home',17)} 投入${money(Math.min(funds,next.cost-next.paid))}，${next.short==='入住'?'添置家具':'建造'+next.short}`:`${icon('check',17)} 完工了`;$('#mode-badge').innerHTML=`<i></i>${preview?'完工预览 · 不影响进度':'施工进度 · '+Math.round(amount/totalCost*100)+'%'} `;$('#toggle-preview span').textContent=preview?'查看施工进度':'看看完工效果';
  const events=state.events.slice(-20).reverse();$('#journal-items').innerHTML=events.length?events.map(e=>`<article class="journal-entry"><div class="entry-icon ${e.type}">${icon(e.type==='study'?'book':e.type==='purchase'?'layers':'home',18)}</div><div><b>${e.type==='study'?`${esc(state.names[e.person])} 学习了 ${e.minutes} 分钟`:e.type==='purchase'?`${esc(state.names[e.person])} 买了 ${esc(itemName(e))}`:`${esc(getPlan(e.plan).name)}：施工投入`}</b><p>${e.type==='study'?esc(e.note||'学习打卡')+(e.rewardVersion===1?`<span class="study-details">${esc(focusLabel(e.focus))} · 投入 ${e.focus}/100 · 本次效率 ${(e.efficiency/100).toFixed(1)}%</span>`:''):e.type==='purchase'?'已放入共同仓库，可以在商店里查看和摆放。':'已从共同余额扣除，施工进度已更新。'}</p></div><div class="entry-meta"><strong>${e.type==='study'?'+ '+money(studyReward(e)):'− '+money(e.amount)}</strong><time>${new Date(e.at).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div></article>`).join(''):`<div class="empty-journal">${icon('book',25)}<div><b>还没有记录</b><p>学完记一下，学习、施工和购买记录都会显示在这里。</p></div><button class="text-button" id="first-study">记一笔 ${icon('arrow',15)}</button></div>`;
  $('#first-study')?.addEventListener('click',openStudy);$('#undo').disabled=!state.events.some(e=>e.type==='study'&&(!isCloud()||e.person===cloud.session.slot));$('#undo').textContent=isCloud()?'撤销我最近一次学习':'撤销最近一次学习';sceneUpdate();shop?.render();designer?.sync();}
$('.catalog-controls').insertAdjacentHTML('beforebegin','<div class="design-entry"><h3>想自己画一个？</h3><p>画房间、开门窗，墙色和地板也能自己挑。</p><button id="design-open">＋ 自己设计户型</button></div><p class="custom-plan-label" id="custom-plan-label" hidden>自己设计的户型</p><div id="custom-plan-cards"></div>');
  $('.market-price').insertAdjacentHTML('afterend','<div class="custom-design-note" id="custom-design-note" hidden>这是你们自己设计的户型，没有对应的真实房价。游戏施工目标仍是 $5,500，改布局不会重置进度。<button id="edit-design">编辑布局、墙色和地板 ↗</button><button id="decorate-design">去商店挑东西 / 摆放物品 ↗</button></div>');
scene=createScene($('#scene'),selectRoom,id=>shop?.openOwned(id));
shop=createShop({getState:()=>state,mutate,getPerson:()=>isCloud()?cloud.session.slot:person,getError:()=>mutationError,toast,showInRoom:async(id,plan)=>{
  if(state.selected!==plan&&!await mutate(s=>({...s,selected:plan}),{type:'select',plan}))return;
  preview=true;interior=true;flat=false;$('#flat-view').hidden=true;$('.scene-wrap').classList.remove('is-flat');document.querySelectorAll('[data-flat]').forEach(b=>b.classList.toggle('active',b.dataset.flat==='false'));$('#cutaway').classList.add('active');$('#exterior').classList.remove('active');selectedRoom=null;$('#room-detail').hidden=true;render();$('.model-panel').scrollIntoView({behavior:'smooth',block:'center'});scene.focusItem?.(id);
}});
$('#invest').insertAdjacentHTML('afterend','<button id="shop-open" class="shop-launch">逛商店 / 摆放物品 ↗</button>');$('#shop-open').onclick=()=>shop.open();
$('#history-nav').insertAdjacentHTML('beforebegin','<button id="shop-nav">商店</button>');$('#shop-nav').onclick=()=>shop.open();
  designer=createDesigner({getState:()=>state,mutate,getError:()=>mutationError,getScope:()=>cloud?.session?.roomId||'local',onSaved:()=>{preview=true;interior=true;flat=false;$('#flat-view').hidden=true;$('.scene-wrap').classList.remove('is-flat');document.querySelectorAll('[data-flat]').forEach(b=>b.classList.toggle('active',b.dataset.flat==='false'));selectedRoom=null;$('#room-detail').hidden=true;$('#cutaway').classList.add('active');$('#exterior').classList.remove('active');render();scene.home();$('.model-panel').scrollIntoView({behavior:'smooth',block:'center'});toast('户型保存好了。可以继续盖房，也可以去商店布置。');}});
  $('#design-open').onclick=()=>designer.open();$('#edit-design').onclick=()=>designer.open(state.selected);$('#decorate-design').onclick=()=>shop.open();render();
function openStudy(){if(isCloud())person=cloud.session.slot;$('#person-select').innerHTML=state.names.map((n,i)=>`<button type="button" class="${person===i?'selected':''}" data-person="${i}" ${isCloud()&&i!==person?'disabled':''}><span class="small-avatar person-${i}">${esc(n.slice(0,1))}</span>${esc(n)}${isCloud()&&i===person?'（我）':''}</button>`).join('');$('#person-select').querySelectorAll('button').forEach(b=>b.onclick=()=>{person=Number(b.dataset.person);$('#person-select').querySelectorAll('button').forEach(n=>n.classList.toggle('selected',n===b));});$('#study-error').textContent='';restorePendingStudy();reward();syncStudyForm();$('#study-dialog').showModal();}
$('#study-open').onclick=openStudy;
function pendingStudy(){return isCloud()&&cloud.session.pending?.action?.type==='study'?cloud.session.pending.action:null;}
function restorePendingStudy(){const pending=pendingStudy();if(!pending)return;$('#minutes').value=pending.minutes;$('#study-note').value=pending.note??'';$('#study-focus').value=pending.focus??DEFAULT_FOCUS;}
function syncStudyForm(){
  const pending=pendingStudy(),locked=studyFormBusy||!!pending;
  for(const input of $('#study-form').querySelectorAll('#minutes,#study-focus,#study-note,[data-minutes]'))input.disabled=locked;
  for(const button of $('#person-select').querySelectorAll('button'))button.disabled=locked||(isCloud()&&Number(button.dataset.person)!==cloud.session.slot);
  const button=$('#study-form button[type=submit]');button.disabled=studyFormBusy;button.innerHTML=(studyFormBusy?'正在保存…':pending?'重试这笔学习':'保存这次学习')+' '+icon('arrow',17);
}
$('#study-form').onsubmit=async e=>{
  e.preventDefault();if(studyFormBusy)return;
  const pending=pendingStudy(),action=pending||{type:'study',minutes:Number($('#minutes').value),note:$('#study-note').value.trim(),focus:Number($('#study-focus').value)};
  const learner=person;studyFormBusy=true;$('#study-error').textContent='';syncStudyForm();
  try{
    const result=await mutate(s=>study(s,{person:learner,minutes:action.minutes,note:action.note,focus:action.focus}),action);
    if(result){
      const saved=state.events.find(event=>event.id===result.requestId&&event.type==='study');
      $('#study-dialog').close();$('#study-note').value='';
      toast(saved?`记好了：${saved.minutes} 分钟，共同余额 +${money(studyReward(saved))}。`:'学习已保存，余额已同步。');
    }else{
      $('#study-error').textContent=mutationError+(pendingStudy()?' 当前时长和投入状态已保留，点「重试这笔学习」继续。':'');
    }
  }finally{studyFormBusy=false;syncStudyForm();}
};
function reward(){
  const minutes=Number($('#minutes').value),focus=Number($('#study-focus').value),label=focusLabel(focus);
  $('#focus-value').textContent=label+' · '+focus;$('#study-focus').setAttribute('aria-valuetext',label+'，'+focus+'/100');$('#study-focus').style.setProperty('--focus-value',focus+'%');
  if(Number.isInteger(minutes)&&minutes>=1&&minutes<=480){const range=rewardRange(minutes,focus);$('#reward-amount').textContent=money(range.min)+' – '+money(range.max);$('#reward-average').textContent='平均约 '+money(range.average);}
  else{$('#reward-amount').textContent='—';$('#reward-average').textContent='填入 1–480 分钟';}
  document.querySelectorAll('[data-minutes]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.minutes)===minutes));
}
document.querySelectorAll('[data-minutes]').forEach(b=>b.onclick=()=>{$('#minutes').value=b.dataset.minutes;reward();});$('#minutes').oninput=reward;$('#study-focus').oninput=reward;reward();
$('#invest').onclick=async()=>{preview=false;if(await mutate(build,{type:'build',plan:state.selected}))toast('资金已投入，施工进度更新了。');};
$('#toggle-preview').onclick=()=>{preview=!preview;render();};
$('#cutaway').onclick=()=>{interior=true;$('#cutaway').classList.add('active');$('#exterior').classList.remove('active');sceneUpdate();};
$('#exterior').onclick=()=>{interior=false;$('#exterior').classList.add('active');$('#cutaway').classList.remove('active');$('#room-detail').hidden=true;sceneUpdate();};
$('#labels-toggle').onchange=e=>{labels=e.target.checked;sceneUpdate();};$('#reset-view').onclick=()=>scene.home();$('#top-view').onclick=()=>scene.top();$('#zoom-in').onclick=()=>scene.zoom(.85);$('#zoom-out').onclick=()=>scene.zoom(1.17);
document.querySelectorAll('[data-flat]').forEach(b=>b.onclick=()=>{flat=b.dataset.flat==='true';$('#flat-view').hidden=!flat;$('.scene-wrap').classList.toggle('is-flat',flat);document.querySelectorAll('[data-flat]').forEach(n=>n.classList.toggle('active',n===b));});
$('#history-nav').onclick=()=>$('#journal').scrollIntoView({behavior:'smooth'});$('#undo').onclick=async()=>{if(await mutate(undoStudy,{type:'undo'}))toast('已撤销最近一次学习记录。');};
$('#settings').onclick=()=>{$('#name-a').value=state.names[0];$('#name-b').value=state.names[1];$('#name-a').disabled=isCloud()&&cloud.session.slot!==0;$('#name-b').disabled=isCloud()&&cloud.session.slot!==1;$('#import-save').disabled=isCloud();$('#save-description').textContent=isCloud()?'记录保存在运行服务的电脑上，页面约每 4 秒同步一次，不用同时在线。电脑关机或休眠时暂停同步。可以导出备份；联机时不能导入本机存档。':'还没联机，记录只保存在这个浏览器里。点右上角「双人联机」就能创建或加入房间。';$('#settings-dialog').showModal();};$('#names-form').onsubmit=async e=>{e.preventDefault();const names=[$('#name-a').value.trim(),$('#name-b').value.trim()];if(await mutate(s=>({...s,names}),{type:'rename',name:names[cloud?.session?.slot??0]})){toast('称呼已保存。');$('#settings-dialog').close();}};
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#export-save').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`together-home-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('存档已导出，留一份备份就好。');};
let pendingImport=null;$('#import-save').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000000)throw Error('存档文件过大。');pendingImport=validate(JSON.parse(await file.text()));$('#import-summary').textContent=`${pendingImport.names.join(' & ')} · ${pendingImport.events.filter(e=>e.type==='study').length} 次学习 · ${inventory(pendingImport).length} 件物品 · 可用资金 ${money(balance(pendingImport))}`;$('#settings-dialog').close();$('#import-dialog').showModal();}catch(err){toast('无法导入：'+err.message);}e.target.value='';};$('#import-cancel').onclick=()=>{$('#import-dialog').close();pendingImport=null;};$('#import-confirm').onclick=()=>{try{if(pendingImport){commit(pendingImport);pendingImport=null;$('#import-dialog').close();toast('存档已恢复。');}}catch(e){toast(e.message);}};
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY&&!isCloud()){try{state=e.newValue?validate(JSON.parse(e.newValue)):freshState();render();toast('已同步另一个标签页的记录。');}catch{toast('另一标签页的存档无法读取，请检查备份。');}}});
if(storageIssue)toast('本机存档暂时无法读取，请先检查备份，避免覆盖旧记录。');

// The shared home uses an independent member credential per device. No credential is
// included in GitHub, in the server URL, or in a routine progress export.
$('.local-status').outerHTML='<button class="local-status" id="sync-open"><i></i><span>双人联机</span></button>';
$('#settings-dialog .settings-block p').id='save-description';
document.body.insertAdjacentHTML('beforeend',`<dialog id="cloud-dialog"><div class="dialog-heading"><div><span class="eyebrow">CONNECT</span><h2>一起开个房间</h2></div><button class="icon-button" id="close-cloud" aria-label="关闭联机窗口">${icon('close')}</button></div><p class="dialog-desc" id="cloud-status"></p><div id="cloud-onboarding"><form id="connect-form"><label class="field-label" for="connect-name">你的称呼</label><input id="connect-name" required maxlength="16" placeholder="比如：小陈" autocomplete="nickname"><label class="field-label" for="invite-code">对方的邀请链接或邀请码 <small>加入时填写</small></label><input id="invite-code" autocomplete="off" placeholder="粘贴对方发来的邀请"><div class="backup-buttons"><button class="primary" type="submit" value="create" id="create-room">创建房间</button><button type="submit" value="join" id="join-room">加入房间</button></div></form><p class="cloud-help">创建后，把邀请链接发给对方。一个房间最多两人，链接只能用一次，7 天内有效。</p><details class="restore-details"><summary>换了设备？用恢复码登录</summary><form id="restore-form"><label class="field-label" for="recovery-input">你自己的恢复码</label><input id="recovery-input" type="password" required autocomplete="off" placeholder="TH1-…"><button class="primary" type="submit">用恢复码登录</button></form></details></div><div id="cloud-connected" hidden><div class="connected-summary" id="connected-summary"></div><div id="invite-area"><button id="make-invite" class="primary">生成邀请链接</button><div id="invite-output" hidden><label class="field-label" for="invite-link">邀请链接 · 发给对方就行</label><input id="invite-link" readonly><button id="copy-invite" class="text-button">复制邀请链接</button></div></div><div class="settings-block"><h3>在其他设备登录</h3><p>恢复码可以登录你的账号，自己保存好。对方用邀请链接加入，不用你的恢复码。</p><button id="copy-recovery" class="text-button">复制我的恢复码</button></div><div class="backup-buttons"><button id="retry-sync">刷新 / 重试未确认操作</button><button id="disconnect">退出当前设备</button></div></div><p class="form-error" id="cloud-error" role="alert"></p><p class="cloud-help">记录保存在运行服务的电脑上。联机时电脑要开着、连着网；关掉网页不会丢记录。</p></dialog>`);
function cloudDialog(){const connected=isCloud();$('#cloud-onboarding').hidden=connected;$('#cloud-connected').hidden=!connected;$('#cloud-error').textContent='';$('#cloud-status').textContent=connected?`当前账号：${state.names[cloud.session.slot]} · ${connectionStatus==='connected'?'已联机':'正在重连'}`:cloud?.configured?'加入同一个房间，就能共享余额和施工进度。':'联机还没配置好，可以先在本机试试。';if(connected){$('#connected-summary').textContent=cloud.session.memberCount===2?`${state.names.join(' & ')}，两个人都加入了。`:'房间开好了，把邀请链接发给对方吧。';$('#invite-area').hidden=cloud.session.slot!==0||cloud.session.memberCount===2;}$('#create-room').disabled=!cloud?.configured;$('#join-room').disabled=!cloud?.configured;}
$('#sync-open').onclick=()=>{cloudDialog();$('#cloud-dialog').showModal();};$('#close-cloud').onclick=()=>$('#cloud-dialog').close();
const incoming=new URLSearchParams(location.hash.slice(1)).get('join');if(incoming)$('#invite-code').value=incoming;
function parseInvite(value){const text=value.trim();if(/^[a-f0-9]{64}$/.test(text))return text;try{const u=new URL(text),code=new URLSearchParams(u.hash.slice(1)).get('join');if(/^[a-f0-9]{64}$/.test(code))return code;}catch{}throw Error('请粘贴完整邀请链接或 64 位邀请码。');}
async function connectionTask(fn){$('#cloud-error').textContent='';$('#connect-form').querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();history.replaceState(null,'',location.pathname+location.search);cloudDialog();toast('已加入房间。');}catch(e){$('#cloud-error').textContent=e.message;}finally{$('#connect-form').querySelectorAll('button').forEach(b=>b.disabled=!cloud.configured);}}
$('#connect-form').onsubmit=e=>{e.preventDefault();const action=e.submitter.value;connectionTask(async()=>{const label=$('#connect-name').value.trim();if(action==='join')await cloud.join(label,parseInvite($('#invite-code').value));else await cloud.create(label);});};
$('#restore-form').onsubmit=e=>{e.preventDefault();connectionTask(()=>cloud.restore($('#recovery-input').value));};
async function copyText(value){try{await navigator.clipboard.writeText(value);toast('已复制。');}catch{const input=document.createElement('textarea');input.value=value;input.style.cssText='position:fixed;left:-10000px';document.body.appendChild(input);input.select();const ok=document.execCommand('copy');input.remove();if(!ok)throw Error('无法自动复制，请手动复制输入框中的内容。');toast('已复制。');}}
$('#make-invite').onclick=async()=>{try{const invite=await cloud.invitation();$('#invite-link').value=location.origin+location.pathname+'#join='+invite;$('#invite-output').hidden=false;toast('邀请链接生成了，旧链接已失效。');}catch(e){$('#cloud-error').textContent=e.message;}};
$('#copy-invite').onclick=()=>copyText($('#invite-link').value).catch(e=>toast(e.message));$('#copy-recovery').onclick=()=>copyText('TH1-'+cloud.session.token).catch(e=>toast(e.message));$('#retry-sync').onclick=async()=>{try{await cloud.retry();cloudDialog();}catch(e){$('#cloud-error').textContent=e.message;}};$('#disconnect').onclick=()=>{if(confirm('先保存好自己的恢复码。退出后记录还在，确定退出当前设备？')){cloud.disconnect();location.reload();}};
cloud=createCloud({onSnapshot(data){const changedPlan=state.selected!==data.state.selected;state=data.state;person=data.slot;if(changedPlan){selectedRoom=null;$('#room-detail').hidden=true;}render();if($('#cloud-dialog').open)cloudDialog();if($('#study-dialog').open)syncStudyForm();},onStatus(status,session){connectionStatus=status;const text=status==='connected'?`已联机 · ${state.names[session.slot]}`:status==='offline'?'暂时离线 · 点这里重连':status==='invalid'?'需要重新登录':status==='unconfigured'?'本机模式 · 联机未配置':'双人联机';$('#sync-open span').textContent=text;$('#sync-open').dataset.status=status;$('footer span:last-child').textContent=isCloud()?'两人共用一份记录 · 服务电脑开机时约每 4 秒同步 · 设置里可导出备份。':'还没联机 · 开个房间，邀请对方一起打卡盖房。';}});
cloud.start().then(()=>{if((incoming||cloud.configured)&&!isCloud()){cloudDialog();$('#cloud-dialog').showModal();}}).catch(e=>{connectionStatus='offline';toast(e.message);});
